# Generated by Django 4.0.1 on 2022-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confcontrol', '0002_price_alter_kuryer_group_kuryer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status_api_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
