# Generated by Django 4.0.1 on 2022-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permisson',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='after_image',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вторая картинка'),
        ),
        migrations.AddField(
            model_name='order',
            name='api',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='before_image',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Первая картинка'),
        ),
        migrations.AddField(
            model_name='order',
            name='step',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_id',
            field=models.BigIntegerField(verbose_name='Оператор ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_name',
            field=models.CharField(max_length=100, verbose_name='Имя оператора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delever',
            field=models.CharField(max_length=500, verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_location',
            field=models.CharField(max_length=2000, verbose_name='Куда доставить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_customer',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_model',
            field=models.CharField(max_length=300, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.CharField(max_length=100, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТИП ОПЛАТЫ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_customer',
            field=models.CharField(max_length=100, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=100, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.CharField(max_length=256, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Заказ оформлен', max_length=512, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_location',
            field=models.CharField(max_length=2000, verbose_name='Откуда забрать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_delever',
            field=models.CharField(max_length=100, verbose_name='ТИП ДОСТАВКА'),
        ),
    ]
