# Generated by Django 4.0.1 on 2022-03-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0002_delete_permisson_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nesu.partner', verbose_name='Партнер'),
        ),
    ]
