# Generated by Django 4.0.1 on 2022-03-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0003_alter_customuser_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_pay',
            field=models.CharField(default=1, max_length=100, verbose_name='ТИП ПРИОБРЕТЕНИЯ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='type_pay',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ТИП ПРИОБРЕТЕНИЯ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nesu.partner', verbose_name='Партнер'),
        ),
    ]
