# Generated by Django 4.0.1 on 2022-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0004_order_type_pay_step_type_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='multi',
            field=models.BooleanField(default=False, verbose_name='МУЛТИДОСТАВКА'),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_delevery',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Корзинка'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_delever1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТИП ДОСТАВКА1'),
        ),
        migrations.AddField(
            model_name='step',
            name='type_delever1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ТИП ДОСТАВКА1'),
        ),
    ]
