# Generated by Django 4.0.1 on 2022-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0005_order_multi_order_parent_delevery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_disc', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('operator', models.BooleanField(default=False, verbose_name='Оператор')),
                ('dispatcher', models.BooleanField(default=False, verbose_name='Диспетчер')),
                ('kuryer', models.BooleanField(default=False, verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delete_message_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='dis_comment',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='order',
            name='multiorder',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Мултизаказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_came',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_location',
            field=models.CharField(max_length=2000, verbose_name='Откуда забрать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_location',
            field=models.CharField(max_length=2000, verbose_name='Куда доставить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_delever1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПЕРСОНАЛНЫЙ ТИП ДОСТАВКА'),
        ),
    ]
