# Generated by Django 4.0.1 on 2022-04-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confcontrol', '0001_initial'),
        ('nesu', '0006_message_order_delete_message_id_order_dis_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispatcher',
        ),
        migrations.DeleteModel(
            name='Kuryer',
        ),
        migrations.DeleteModel(
            name='Kuryer_group',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='partner',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confcontrol.partner', verbose_name='Партнер'),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
