# Generated by Django 4.0.1 on 2022-04-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confcontrol', '0002_price_alter_kuryer_group_kuryer_id'),
        ('nesu', '0007_delete_dispatcher_delete_kuryer_delete_kuryer_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disp_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField()),
                ('step', models.BigIntegerField(blank=True, default=0)),
                ('obj', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kuryer_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField()),
                ('step', models.BigIntegerField(blank=True, default=0)),
                ('obj', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='a',
            field=models.IntegerField(default=0, verbose_name='Цена пункта A'),
        ),
        migrations.AddField(
            model_name='order',
            name='b',
            field=models.IntegerField(default=0, verbose_name='Цена пункта B'),
        ),
        migrations.AddField(
            model_name='order',
            name='b1',
            field=models.IntegerField(default=0, verbose_name='Цена пункта B(0.1-5 Кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='b2',
            field=models.IntegerField(default=0, verbose_name='Цена пункта B(5.1-10 Кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='b3',
            field=models.IntegerField(default=0, verbose_name='Цена пункта B(10.1-20 Кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='comis',
            field=models.IntegerField(default=0, verbose_name='Комиссия NesuVezu %'),
        ),
        migrations.AddField(
            model_name='order',
            name='done_time',
            field=models.CharField(blank=True, default='', max_length=521, verbose_name='Время завершение доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Масса'),
        ),
        migrations.AddField(
            model_name='step',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Масса'),
        ),
        migrations.CreateModel(
            name='Pay_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name='Начало период')),
                ('datetime_apply', models.DateField(null=True, verbose_name='Конец период')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confcontrol.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Оплата партнеров',
                'verbose_name_plural': 'Оплата партнеров',
            },
        ),
        migrations.CreateModel(
            name='Pay_kuryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name='Начало период')),
                ('datetime_apply', models.DateField(null=True, verbose_name='Конец период')),
                ('kuryer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confcontrol.kuryer', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Оплата курьерам',
                'verbose_name_plural': 'Оплата курьерам',
            },
        ),
    ]
