# Generated by Django 4.0.1 on 2022-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesu', '0008_disp_step_kuryer_step_order_a_order_b_order_b1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Масса'),
        ),
    ]
